name: labyrinth
description: The official app for GDSC Shiv Nadar University's Labyrinth 2022 event.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  connectivity_plus: ^2.2.1
  delayed_display: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bounce: ^1.1.0
  flutter_native_splash: ^2.0.4
  google_fonts: ^2.3.1
  http: ^0.13.4
  liquid_swipe: ^2.1.1
  provider: ^6.0.2
  rounded_loading_button: ^2.0.9
  shared_preferences: ^2.0.13
  simple_gradient_text: ^1.2.2
  url_launcher: ^6.0.20
  confetti: ^0.6.0
  mobile_scanner: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/labyrinth_logo.png"

flutter_native_splash:
  color: "#140223"
  image: assets/images/labyrinth_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: NeueMachina
      fonts:
        - asset: assets/fonts/NeueMachina-Regular.otf
        - asset: assets/fonts/NeueMachina-Light.otf
          weight: 300
        - asset: assets/fonts/NeueMachina-Ultrabold.otf
          weight: 900
